defaults: &defaults
  roles:
    - admin
    - owner
    - user
  default_role: user
  genders:
    - Feminine
    - Masculine
    - Undefined
  default_gender: Undefined

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
