defaults: &defaults
  roles:
    - admin
    - owner
    - user
  default_role: user
  genders:
    - female
    - male
    - 'other or decline to state'
  default_gender: 'other or decline to state'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
